altexo_frontend_chat_run:
  image: nginx:1.11.10
  container_name: altexo-frontend-chat-run
  volumes:
    - ./build:/usr/share/nginx/html:ro
    - ./scripts/config/nginx-locations-dev-docker.conf:/etc/nginx/nginx.conf:ro
    - /etc/ssl/altexo.com/altexo.com.crt:ro
    - /etc/ssl/altexo.com/altexo.com.key:ro
  environment:
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - VIRTUAL_PORT=${VIRTUAL_PORT}
